name: Run prettier, eslint and stylelint in changed files from this PR

on:
  pull_request:
    branches: ['master']

env:
  STORE_PATH: .pnpm-store
  NODE_VERSION: 18.18.2

jobs:
  install-deps:
    uses: ./.github/workflows/install-deps.yml
    with:
      NODE_VERSION: 18.18.2
      PNPM_VERSION: 8

  code-style:
    runs-on: ubuntu-latest
    name: code-style
    steps:
      - name: Get all code files, Get all style files, Get all changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files_yaml: |
            code:
              - '**.js'
              - '**.ts'
              - '**.tsx'
              - '**.jsx'
              - '**.mjs'
              - '**.cjs'
            style:
              - '**.scss'
              - '**.css'
            all:
              - '!pnpm-lock.yaml'
              - '**.*'

      - name: Run eslint in code files
        if: steps.changed-files.outputs.code_any_changed == 'true'
        env:
          files: ${{ steps.changed-files.outputs.code_all_changed_files }}
        run: pnpm exec eslint $files --report-unused-disable-directives --max-warnings 0

      - name: Run stylelint in scss files
        if: steps.changed-files.outputs.style_any_changed == 'true'
        env:
          files: ${{ steps.changed-files.outputs.style_all_changed_files }}
        run: pnpm exec stylelint $files --allow-empty-input

      - name: Run prettier in all files
        if: steps.all-changed-files.outputs.all_any_changed == 'true'
        env:
          files: ${{ steps.all-changed-files.outputs.all_all_changed_files }}
        run: pnpm exec prettier $files --check --ignore-unknown
