name: Playwright Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
      - uses: actions/checkout@v3

      - name: Setup deps
        uses: ./.github/actions/install-deps

      - name: Run your tests
        run: npx playwright test
        env:
          HOME: /root

      - name: Run e2e tests
        run: pnpm test:e2e

      - name: Run ct tests
        run: pnpm test:ct
