name: Node.js CI

on:
  push:
    branches: ['master', 'develop']
  pull_request:
    branches: ['master', 'develop']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and build
        run: |
          pnpm install
          pnpm build

      - name: Run Vitest tests
        run: pnpm test --watch=false

      - name: Lint tests
        run: pnpm lint

      - name: Stylelint tests
        run: pnpm stylelint
