name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup deps
        uses: devhatt/workflows/.github/actions/pnpm-setup.yml@main

      - name: Run unit Tests
        run: pnpm test:coverage --silent

      - name: 'Report Coverage'
        if: ${{ always() && !github.event.pull_request.head.repo.fork }}
        uses: davelosert/vitest-coverage-report-action@v2

      - name: 'Upload Coverage'
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Build
        run: pnpm build
  e2e:
    needs: [build]
    uses: devhatt/workflows/.github/workflows/playwright-tests.yml@main
    with:
      pnpm-version: '8'
      node-version: '20'
