name: Node.js CI

on:
  push:
    branches: ['master', 'develop']
  pull_request:
    branches: ['master', 'develop']

jobs:
  install-deps:
    uses: ./.github/workflows/install-deps.yml
    with:
      NODE_VERSION: 18.18.2
      PNPM_VERSION: 8

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install e2e dependencies
        run: pnpm playwright install --with-deps

      - name: Run unit Tests
        run: pnpm test --silent

      - name: Run e2e tests
        run: pnpm test:e2e

      - name: Run ct tests
        run: pnpm test:ct

      - name: Build
        run: pnpm build
