name: Node.js CI

on:
  push:
    branches: ['master', 'develop']
  pull_request:
    branches: ['master', 'develop']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: code checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install and build
      - run: yarn install && yarn build

      - name: jest tests
      - run: yarn test --watchAll=fals

      - name: lint tests
      - run: yarn lint

      - name: stylelint tests
      - run: yarn stylelint
